image:
  file: .gitpod.Dockerfile

# tasks:
#   - name: Install Dependencies
#     init: R -e "install.packages('languageserver', repos='https://cran.r-project.org/')"

vscode:
  extensions:
    - reditorsupport.r
    - ms-toolsai.jupyter
    - ms-python.python
